---
title: "03_Background"

knit: (function(input, encoding) {
  rmarkdown::render(input,
                    encoding = "UTF-8",
                    output_dir = "../html",
                    knit_root_dir = rprojroot::find_rstudio_root_file())})
output: 
  html_document
---


```{r child = 'src/00_loader.Rmd', Include = TRUE, eval = FALSE}
```

The Olympic games was first held in Athens in 1896, with 241 athletes and 14 nations. They participated in 43 events. These events were inspired from the ancient Olympic games that were held in Greece from 8th century BC to the 4th century AD [@a2020_olympic]. The list of the events for this Olympics appears in Table \@ref(tab:SummerWinners). These Olympics become known as the Summer Olympic Games.

In 1921, the decision was made to make a Winter Olympic games to cater for snow and ice sports. The data set that I obtained contains data from the 1924 Winter Olympic Games and the list of these sports can be found in Table \@ref(tab:WinterWinners).

[@OxfordStudy] and their 2016 Olympic Study found on average it costs approx 5.2 billion US to host a Summer Olympics and 3.1 billion US to host the Winter Olympic games. This figure did not include upgrades and improvements to the hosts major infrastructure such as airports and highways.

Further costs are incurred for the opening and closing ceremonies, and medal presentations. There are three types of medals, Gold for first place, Silver for second and Bronze for third place finishers. These medals are regarded as highly prestigious and brings great pride to the athlete and the host nation when they possess them.

Every athlete that competes in these games must belong to a host nation. These nations are managed by a National Olympic Committee (NOC). This body ensures that the games are run in the interest of fairness and good sportsmanship by all countries. This can be by way of sport rules and education for all involved. It is this body that is responsible for nominating their candidates interest in hosting the future games [a2025_what].

Due to the size of the events, they bring in many competitors and fans for the spectacle. This in turn raises the cost of travel to the host nations during the competition window. It is these costs that the non-host nation wish to minimize whilst still able to procure the most medals possible. This is the problem that this paper is looking to assist with. 

[@heazlewood_2006_prediction] has some analysis regarding models to predict the optimal athlete numbers for all swimming events. This article was able to make some of these predictions, however, improvements are needed to apply these results to athletics and swimming across the various distances of the races. These models are applied to results from 2004 and earlier. This article is of particular interest because of the break down of athletes into sections, mainly swimming. It could be useful to attempt to extend their results to apply it to other sports, such as athletics in summer or cross country skiing in winter. Whilst this is similar to my investigations, I feel it is at a deeper level and more specific to swimming only. I try and stay across all sports, looking for trends and medals to proportion of athletes sent to the games. I also investigate the trends with changes in the numbers of athletes sent for a particular sport.

Now that we have obtained a data set, we take a look at some questions that will guide the exploration of this data.