---
title: "08_Conclude"
knit: (function(input, encoding) {
  rmarkdown::render(input,
                    encoding = "UTF-8",
                    output_dir = "../html",
                    knit_root_dir = rprojroot::find_rstudio_root_file())})
output: 
  html_document
---

In conclusion, I looked into the changes in the Olympic games from their inception in 1896 for the Summer Olympic games and in 1924 Winter Olympics. I found that there are an increasing number of sports being introduced into both types of games. There is some sports that are no longer participated in such as Military Ski Patrol. I discovered that the number of medals awarded is not proportionate to the number of athletes that you send. Sending less athletes and having them compete in multiple events did not equate to less medals if those athletes are up to the job. There is a trend towards increasing participation in Athletic events, whilst larger sporting events such as swimming, and gymnastics have quite a large participation and have stabilized in participation numbers.
