---
title: "06_DataDescription"
knit: (function(input, encoding) {
  rmarkdown::render(input,
                    encoding = "UTF-8",
                    output_dir = "../html",
                    knit_root_dir = rprojroot::find_rstudio_root_file())})
output:
  pdf_document
  
editor_options: 
  chunk_output_type: console
bibliography: DSAA811.bib
link-citations: TRUE
citation_package: apa-annotated.csl
---

```{r child = 'src/00_loader.Rmd', Include = TRUE, eval = FALSE}
```

```{r mapplaying, fig.align = 'center', warning = FALSE, echo = FALSE}

drawMap("", "Every athlete locations")

drawMap("Winter", "Location of the winter athletes")
```

```{r SummerPlayers, fig.align = 'center', warning = FALSE, echo = FALSE}

drawMap("Summer", "Location of the summer athletes")

```



\newpage

<!-- This section is from the original Background
I have been looking into some articles regarding the statistics around reducing the number of athletes that a country can send to the Olympics to procure the maximum medals. The following three articles are of interest, and depending on the information, I can extract from my dataset. One of these avenues will become the focus element for this report.

[@haut_2014_nothing] examines the statistics of the Olympics but also investigates the data from the perspective of increasing funds to rural areas to enhance performance and ultimately achieve more winners. At this stage I don't think that this report will be useful, however there is some regional information in my data set that I can use to plot the locations of the athletes on a world map.


[@condon_1999_predicting] Uses neural networks to produce three models that look at winners from a country perspective using data up until 1996. If I can get the same results, my data set continues to 2016, so this avenue would allow me to extend their findings on the years post 1996 to 2016.


[@heazlewood_2006_prediction] Looks into creating models to predict the optimal athlete numbers for all swimming events. This article was able to make some of these predictions, but improvements are needed to apply these results to athletics and swimming across the various distances of the races. These models are applied to results from 2004 and earlier. This article is of particular interest because of the break down of athletes into sections, mainly swimming. It could be useful to attempt to extend their results to apply it to other sports, such as athletics in summer or cross country skiing in winter.

Some of the terminology that I have come across is NOC or National Olympic Committee. Each country has a member that is on the committee and they are responsible for that country. Every athlete must compete under their NOC. I can used this NOC to get a general location of the athletes home town when comparing countries for athlete levels. -->


<!-- This was the research question part

As this is in the early stages of investigation, I still have too many questions to look into.

I can look at athletes, per winter or summer games, per country that the athlete competes at, or per NOC. I can even split the data into per sport. At the end of the day I want to answer, what is the minimal number of athletes that my country should send to the games to receive the most medals based on previous summer and winter Olympic data.

My plan moving forward is to play with the data set some more to see if I can marry the results of prior written research so I can stand on the giants of the past to push the research in this area forward in the future.

-->